xorgdata/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

import xorgdata.alumnforce.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots'),
    path('', xorgdata.alumnforce.views.SummaryView.as_view(), name='index'),
    path('issues', xorgdata.alumnforce.views.IssuesView.as_view(), name='issues'),
]

xorgdata/alumnforce/models.py
from django.core.validators import validate_comma_separated_integer_list
from django.db import models
from django.utils.translation import ugettext_lazy as _

from xorgdata.utils.fields import DottedSlugField, UnboundedCharField


class Account(models.Model):
    # User kinds defined by the AX
    KIND_GRADUATED = 1
    KIND_EMPLOYEE = 3
    KIND_STUDENT = 5
    KIND_VISITOR = 7
    KIND_ASSOCIATED_MEMBER = 9
    KIND_WIDOW = 10
    KINDS = {
        KIND_GRADUATED: "Diplômé(e)",
        KIND_EMPLOYEE: "Personnel de l'AX",
        KIND_STUDENT: "Élève/Étudiant(e)",
        KIND_VISITOR: "Visiteur",
        KIND_ASSOCIATED_MEMBER: "Membre associé",
        KIND_WIDOW: "Veuves/Veufs",
    }
    # Roles defined by the AX
    ROLE_GUEST = 1
    ROLE_SUPER_ADMIN = 2
    ROLE_TOTAL_ADMIN = 3
    ROLE_GRADUATED = 4
    ROLE_CONTRIBUTOR = 5
    ROLE_STUDENT = 7
    ROLE_SUBSCRIBED = 17
    ROLE_ASSOCIATED_MEMBER = 19
    ROLE_CONTENT_ADMIN = 21
    ROLE_ACCOUNTING_ADMIN = 22
    ROLE_WIDOW = 26
    ROLES = {
        ROLE_GUEST: "Visiteur",
        ROLE_SUPER_ADMIN: "Super-administrateur",
        ROLE_TOTAL_ADMIN: "Administrateur total",
        ROLE_GRADUATED: "Diplômé",
        ROLE_CONTRIBUTOR: "Cotisant",
        ROLE_STUDENT: "Élève et étudiant",
        ROLE_SUBSCRIBED: "Abonné",
        ROLE_ASSOCIATED_MEMBER: "Membre associé",
        ROLE_CONTENT_ADMIN: "Administrateur contenu",
        ROLE_ACCOUNTING_ADMIN: "Administrateur comptable",
        ROLE_WIDOW: "Veuves/Veufs",
    }

    af_id = models.IntegerField(primary_key=True)
    ax_id = models.CharField(max_length=20, blank=True, null=True)
    first_name = UnboundedCharField()
    last_name = UnboundedCharField()
    common_name = UnboundedCharField(blank=True)
    civility = UnboundedCharField(blank=True)
    birthdate = models.DateField(blank=True, null=True)
    address_1 = UnboundedCharField(blank=True)
    address_2 = UnboundedCharField(blank=True)
    address_3 = UnboundedCharField(blank=True)
    address_4 = UnboundedCharField(blank=True)
    address_postcode = UnboundedCharField(blank=True)
    address_city = UnboundedCharField(blank=True)
    address_state = UnboundedCharField(blank=True)
    address_country = models.CharField(max_length=2, blank=True)
    address_npai = models.NullBooleanField()
    phone_personnal = UnboundedCharField(blank=True)
    phone_mobile = UnboundedCharField(blank=True)
    email_1 = models.EmailField()
    email_2 = models.EmailField(blank=True)
    nationality = UnboundedCharField(blank=True)
    nationality_2 = UnboundedCharField(blank=True)
    nationality_3 = UnboundedCharField(blank=True)
    dead = models.NullBooleanField()
    deathdate = models.DateField(blank=True, null=True)
    dead_for_france = UnboundedCharField(blank=True)
    user_kind = models.IntegerField()
    additional_roles = UnboundedCharField(blank=True,
                                          validators=[validate_comma_separated_integer_list])
    xorg_id = DottedSlugField(max_length=255, blank=True, null=True)
    school_id = UnboundedCharField(blank=True)
    admission_path = UnboundedCharField(blank=True)
    cursus_domain = UnboundedCharField(blank=True)
    cursus_name = UnboundedCharField(blank=True)
    corps_current = UnboundedCharField(blank=True)
    corps_origin = UnboundedCharField(blank=True)
    corps_grade = UnboundedCharField(blank=True)
    nickname = UnboundedCharField(blank=True)
    sport_section = UnboundedCharField(blank=True)
    binets = UnboundedCharField(blank=True)
    mail_reception = UnboundedCharField(blank=True)
    newsletter_inscriptions = UnboundedCharField(blank=True)
    profile_picture_url = UnboundedCharField(blank=True)
    last_update = models.DateField()
    deleted_since = models.DateField(blank=True, null=True)

    def __str__(self):
        """Get a string identifying an account"""
        # Start by the X.org ID or names or email
        if self.xorg_id:
            result = self.xorg_id
        elif self.first_name and self.last_name:
            result = '{} {}'.format(self.first_name, self.last_name)
        elif self.email_1:
            result = self.email_1
        else:
            result = '?'

        # Add the AX ID or the AF ID
        if self.ax_id:
            result += ' (AX ID {})'.format(self.ax_id)
        else:
            result += ' (AF ID {})'.format(self.af_id)
        return result

    def get_additional_roles(self):
        """Return the additional roles as a list of integers"""
        if not self.additional_roles:
            return []
        return [int(r) for r in self.additional_roles.split(',')]

    @property
    def alumnforce_profile_url(self):
        """URL on AlumnForce website"""
        return 'https://ax.polytechnique.org/person/by-id/{:d}'.format(self.af_id)


class AcademicInformation(models.Model):
    account = models.ForeignKey('Account', related_name='degrees', on_delete=models.CASCADE)
    diploma_reference = UnboundedCharField()
    diplomed = models.NullBooleanField()
    diplomation_date = models.DateField(blank=True, null=True)
    cycle = UnboundedCharField(blank=True)
    domain = UnboundedCharField(blank=True)
    name = UnboundedCharField(blank=True)
    last_update = models.DateField()


class ProfessionnalInformation(models.Model):
    account = models.ForeignKey('Account', related_name='jobs', on_delete=models.CASCADE)
    title = UnboundedCharField()
    role = UnboundedCharField(blank=True)
    company_name = UnboundedCharField()
    address_1 = UnboundedCharField(blank=True)
    address_2 = UnboundedCharField(blank=True)
    address_3 = UnboundedCharField(blank=True)
    address_4 = UnboundedCharField(blank=True)
    address_postcode = UnboundedCharField(blank=True)
    address_city = UnboundedCharField(blank=True)
    address_country = UnboundedCharField(blank=True)
    phone_indicator = models.IntegerField(blank=True, null=True)
    phone_number = UnboundedCharField(blank=True)
    mobile_phone_indicator = models.IntegerField(blank=True, null=True)
    mobile_phone_number = UnboundedCharField(blank=True)
    fax = UnboundedCharField(blank=True)
    email = models.EmailField(blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    contract_kind = UnboundedCharField(blank=True)
    current = models.NullBooleanField()
    creator_of_company = models.NullBooleanField()
    buyer_of_company = models.NullBooleanField()
    last_update = models.DateField()


class Group(models.Model):
    af_id = models.IntegerField(primary_key=True)
    ax_id = models.CharField(max_length=20, blank=True, null=True, unique=True)
    url = UnboundedCharField(blank=True)
    name = UnboundedCharField(blank=True)
    category = UnboundedCharField(blank=True)
    last_update = models.DateField()

    def __str__(self):
        return "%s (AF ID %s)" % (self.name, self.af_id)


class GroupMembership(models.Model):
    # Use memership values defined by Alumnforce
    MEMBERSHIP_ROLES = (
        ('banned', _('banned')),
        ('invited', _('invited')),
        ('member', _('member')),
        ('moderator', _('moderator')),
        ('onlist', _('on list')),
        ('responsible', _('responsible')),
        ('unsubscribed', _('unsubscribed')),
    )
    # Roles that really mean that the user belongs to the group
    IN_GROUP_ROLES = frozenset(('member', 'moderator', 'onlist', 'responsible'))
    account = models.ForeignKey(Account, related_name='group_memberships', on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    role = models.SlugField(choices=MEMBERSHIP_ROLES)
    last_update = models.DateField()

    class Meta:
        unique_together = ('group', 'account')


class ImportLog(models.Model):
    # Kind of export file. Order is important as it determines the order used to
    # parse incoming export files: users need to be first created, then groups,
    # then everything else (that depends on users and/or groups).
    KNOWN_EXPORT_KINDS = (
        ('users', _('users')),
        ('groups', _('groups')),
        ('groupmembers', _('groupmembers')),
        ('userdegrees', _('userdegrees')),
        ('userjobs', _('userjobs')),
    )
    # Error code when importing data
    SUCCESS = 0
    ALUMNFORCE_ERROR = 1
    XORG_ERROR = 2
    ERROR_CODES = (
        (SUCCESS, _('success')),
        (ALUMNFORCE_ERROR, _('AlumnForce error')),
        (XORG_ERROR, _('X.org error')),
    )
    date = models.DateField()
    export_kind = models.SlugField(choices=KNOWN_EXPORT_KINDS)
    is_incremental = models.BooleanField()
    error = models.IntegerField(choices=ERROR_CODES)
    num_modified = models.IntegerField(null=True, blank=True)
    message = UnboundedCharField(blank=True)


class ExportLog(models.Model):
    KIND_AUTH = 'auth'
    KNOWN_KINDS = (
        (KIND_AUTH, _('X.org auth')),
    )
    SUCCESS = 0
    ERROR_CODES = (
        (SUCCESS, _('success')),
    )
    date = models.DateField()
    export_kind = models.SlugField(choices=KNOWN_KINDS)
    error = models.IntegerField(choices=ERROR_CODES)
    num_items = models.IntegerField(null=True, blank=True)
    message = UnboundedCharField(blank=True)

xorgdata/alumnforce/views.py
import re

from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Count
from django.views.generic import TemplateView

from xorgdata.alumnforce import models


class SummaryView(TemplateView):
    template_name = 'xorgdata/summary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get the last import logs from the database, for each defined kind
        last_logs = []
        for kind, _kind_name in models.ImportLog.KNOWN_EXPORT_KINDS:
            qs = models.ImportLog.objects.filter(export_kind=kind).order_by('-date', '-is_incremental')
            try:
                last_logs.append(qs[:1].get())
            except models.ImportLog.DoesNotExist:
                pass
        context['last_imp_logs_by_kind'] = last_logs

        # Get the last export logs from the database, for each defined kind
        last_logs = []
        for kind, _kind_name in models.ExportLog.KNOWN_KINDS:
            qs = models.ExportLog.objects.filter(export_kind=kind).order_by('-date')
            try:
                last_logs.append(qs[:1].get())
            except models.ExportLog.DoesNotExist:
                pass
        context['last_exp_logs_by_kind'] = last_logs
        return context


class IssuesView(UserPassesTestMixin, TemplateView):
    template_name = 'xorgdata/issues.html'

    def test_func(self):
        """Restrict this view to the superuser"""
        return self.request.user.is_superuser

    def find_issues(self, account):
        """Find issues in an account"""
        account_issues = []

        if account.civility not in ('', 'Mme', 'M'):
            account_issues.append("Unknown civility {}".format(repr(account.civility)))

        if account.user_kind not in models.Account.KINDS:
            account_issues.append("Unknown account kind {}".format(account.user_kind))

        try:
            account_roles = account.get_additional_roles()
        except ValueError:
            account_issues.append("Invalid additional roles value {}".format(repr(account.additional_roles)))
        else:
            for role in account_roles:
                if role not in models.Account.ROLES:
                    account_issues.append("Unknown account role {}".format(role))

        if account.xorg_id:
            # Verify the format of X.org ID
            if re.search(r'[^a-z0-9.-]', account.xorg_id):
                account_issues.append("Invalid X.org ID: {}".format(repr(account.xorg_id)))
        else:
            # Check whether the user should have a X.org ID
            if account.user_kind == models.Account.KIND_GRADUATED:
                account_issues.append("Missing X.org ID for graduated")
            elif account.user_kind == models.Account.KIND_STUDENT:
                account_issues.append("Missing X.org ID for student")

        # Verify email addresses against a simple regular expression
        email_regexp = re.compile(r'^[a-zA-Z0-9._+-]+@[a-zA-Z0-9.-]+$')
        if account.email_1 and not email_regexp.match(account.email_1):
            account_issues.append("Invalid email address 1 {}".format(repr(account.email_1)))
        if account.email_2 and not email_regexp.match(account.email_2):
            account_issues.append("Invalid email address 2 {}".format(repr(account.email_2)))
        return account_issues

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Find accounts with duplicate IDs
        duplicated_ax_id = {
            row['ax_id']: row['count']
            for row in models.Account.objects
            .filter(deleted_since=None)
            .exclude(ax_id=None)
            .values('ax_id')
            .annotate(count=Count('af_id'))
            .filter(count__gt=1)
        }
        duplicated_xorg_id = {
            row['xorg_id']: row['count']
            for row in models.Account.objects
            .filter(deleted_since=None)
            .exclude(xorg_id=None)
            .values('xorg_id')
            .annotate(count=Count('af_id'))
            .filter(count__gt=1)
        }
        duplicated_school_id = {
            row['school_id']: row['count']
            for row in models.Account.objects
            .filter(deleted_since=None)
            .exclude(school_id='')
            .values('school_id')
            .annotate(count=Count('af_id'))
            .filter(count__gt=1)
        }

        issues = []
        for account in models.Account.objects.filter(deleted_since=None):
            account_issues = self.find_issues(account)
            dup_count = duplicated_ax_id.get(account.ax_id)
            if dup_count is not None:
                account_issues.append("Duplicated AX ID {}, shared with {} accounts".format(
                    repr(account.ax_id), dup_count))

            dup_count = duplicated_xorg_id.get(account.xorg_id)
            if dup_count is not None:
                account_issues.append("Duplicated X.org ID {}, shared with {} accounts".format(
                    repr(account.xorg_id), dup_count))

            dup_count = duplicated_school_id.get(account.school_id)
            if dup_count is not None:
                account_issues.append("Duplicated school ID {}, shared with {} accounts".format(
                    repr(account.school_id), dup_count))

            if account_issues:
                issues.append({
                    'account': account,
                    'issues': account_issues,
                })
        context['issues'] = issues
        return context

xorgdata/templates/xorgdata/issues.html
{% extends 'base.html' %}

{% block title %}
X.org Data issues
{% endblock %}
{% block head_content %}
    <style type="text/css"><!--
        a {
            text-decoration: none;
            color: blue;
        }
        a:hover {
            text-decoration: underline;
        }
    --></style>
{% endblock %}
{% block body_content %}
    <h1>Issues found in AX database</h1>
    <p>Issues need to be fixed in <a href="https://ax.polytechnique.org/profile/manager/index">AX's website</a>.</p>
    <table width="100%" border="1">
        <tr>
            <th width="20%">Accounts ({{ issues | length }})</th>
            <th>Issues</th>
        </tr>
        {% for account_and_issues in issues %}
        <tr>
            <td>
            {% with account=account_and_issues.account %}
                {{ account }} (<a href="{{ account.alumnforce_profile_url }}">AX</a>, <a href="{% url 'admin:alumnforce_account_change' account.af_id %}">admin</a>)
            {% endwith %}
            </td>
            <td>
                <ul>
                    {% for issue in account_and_issues.issues %}
                    <li>{{ issue }}
                    {% endfor %}
                </ul>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

xorgdata/templates/xorgdata/summary.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
X.org Data synchronization summary
{% endblock %}
{% block head_content %}
    <style type="text/css"><!--
        a {
            text-decoration: none;
        }

        .xorg-spinner, .xorg-spinner * {
            box-sizing: border-box;
            border: none;
        }

        .xorg-spinner {
            height: 400px;
            width: 400px;
            position: absolute;
            top: calc(50% - (400px * 0.5));
            left: calc(50% - (400px * 0.5));
            overflow: hidden;
        }

        .xorg-spinner table {
            z-index: 1;
        }
        td.export-title {
            text-align: center;
        }
        td.export-kind {
            font-family: monospace;
            text-align: right;
        }
        td.export-result {
            text-align: left;
        }

        .ax-logo {
            float: left;
        }
        .xorg-logo {
            float: right;
        }
        .xorg-logo img {
            border-radius: 50%;
        }
        .ax-logo, .xorg-logo {
            animation: logo-animation 3s linear infinite;
            border: none;
            opacity: 1.0;
            z-index: 1;
        }

        @keyframes logo-animation {
            70% {
                opacity: 0.3;
            }
        }

        .xorg-spinner .spinner-inner {
            position: relative;
            display: block;
            height: 100%;
            width: 100%;
        }
        .xorg-spinner .spinner-line {
            position: absolute;
            width: 100%;
            height: 100%;
            border-radius: 50%;
            animation-duration: 5s;
            border-right-width: calc((400px * 2) / 25);
            border-top-width: calc((400px * 2) / 25);
            border-right-style: solid;
            border-top-style: solid;
            border-top-color: transparent;
        }

        .xorg-spinner .spinner-line:nth-child(1) {
            animation: xorg-spinner-animation-1 3s linear infinite;
            transform: rotateZ(120deg) rotateX(66deg) rotateZ(0deg);
            border-right-color: #003c57;
            opacity: 0.5;
            z-index: -1;
        }
        .xorg-spinner .spinner-line:nth-child(2) {
            animation: xorg-spinner-animation-2 3s linear infinite;
            transform: rotateZ(120deg) rotateX(66deg) rotateZ(180deg);
            border-right-color: #5284a5;
            opacity: 0.5;
            z-index: -1;
        }

        @keyframes xorg-spinner-animation-1 {
            33% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(-120deg);
            }
            67% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(-240deg);
            }
            100% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(-360deg);
            }
        }

        @keyframes xorg-spinner-animation-2 {
            33% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(60deg);
            }
            67% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(-60deg);
            }
            100% {
                transform: rotateZ(120deg) rotateX(66deg) rotateZ(-180deg);
            }
        }
        .xorg-ribbon {
            position: fixed;
            right: -3em;
            bottom: 3.5em;
            background-color: #5284a5;
            transform: rotate(-45deg);
            padding: 5px;
            width: 15em;
            border-color: #88aaee;
            border-style: dotted none dotted none;
            border-width: 2px;
            color: white;
            text-align: center;
            z-index: -2;
        }
    --></style>
{% endblock %}
{% block body_content %}
    <div class="xorg-spinner">
        <div class="spinner-inner">
            <div class="spinner-line"></div>
            <div class="spinner-line"></div>
            <a class="ax-logo" href="https://ax.polytechnique.org/">
                <img alt="AX" src="{% static 'logo-ax.png' %}">
            </a>
            <a class="xorg-logo" href="https://www.polytechnique.org/">
                <img alt="Polytechnique.org" src="{% static 'logo-xorg-for-circle.png' %}">
            </a>
            <table style="width: 100%;">
                <tr><td class="export-title" colspan="2">&mdash;&mdash;&nbsp;Import from AX&nbsp;&mdash;&mdash;</td></tr>
            {% for log_obj in last_imp_logs_by_kind %}
                <tr>
                    <td class="export-kind">{{ log_obj.get_export_kind_display }}</td>
                    <td class="export-result">{{ log_obj.get_error_display }} on {{ log_obj.date|date:"Y-m-d" }}</td>
                </tr>
            {% endfor %}
                <tr><td class="export-title" colspan="2">&mdash;&mdash;&nbsp;Export&nbsp;&mdash;&mdash;</td></tr>
            {% for log_obj in last_exp_logs_by_kind %}
                <tr>
                    <td class="export-kind">{{ log_obj.get_export_kind_display }}</td>
                    <td class="export-result">{{ log_obj.get_error_display }} on {{ log_obj.date|date:"Y-m-d" }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
    <a href="https://github.com/Polytechnique-org/xorgdata/issues" class="xorg-ribbon">
        Report issues on GitHub
    </a>
{% endblock %}